//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesForHands2.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long idObject { get; set; }
        public string ObjectName { get; set; }
        public Nullable<int> CountBefore { get; set; }
        public Nullable<int> CountNow { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
