//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesForHands2.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MaterialDetails
    {
        public string Type { get; set; }
        public string Material_name { get; set; }
        public int Count { get; set; }
        public Nullable<int> Supplier_count { get; set; }
        public string Price { get; set; }
        public Nullable<int> CountBefore { get; set; }
        public string Description { get; set; }
    }
}
